### ISSUE TITLE
Wiki fails to download due to not enough retries, missing options retry and delay

### ISSUE THREAD

**Issue by retro-mouse** [saveweb/dokuwiki-dumper#6]
I have needed to edit the hardcoded retry of 5 to 30 backoff_factor from 1.5 to 2 on the source: /dokuWikiDumper/utils/session.py

To be able to dump: https://www.ff6hacking.com/wiki/doku.php 

I would like to suggest to expose retry and backoff_factor as retry and delay the same way the older dumpgenerator.py has.

**Comment by yzqzss** [comment]
> ... to expose retry and backoff_factor ...

Good idea

> delay the same way the older dumpgenerator.py has.

DokuWiki is lighter than MediaWiki, so even low-end server can handle lots of traffic without any problems. No need to slow things down like dumpgenerator. But if you run into a pesky WAF, adding some delay is reasonable.

**Comment by yzqzss** [comment]
Done.

delay: c65911f58c1d531cf0ab59450ebea42b36e1f28f
retry: 05802fdde41fe6e6ffab8564f0e4dea572ff1cd1
