### ISSUE TITLE
Suggestion: about the folder download

### ISSUE THREAD

**Issue by Exorcism0666** [saveweb/dokuwiki-dumper#9]
Why not add to the program, the permission to delete the downloaded folder after uploading it to IA ?

**Comment by Exorcism0666** [comment]
😭 
![image](https://user-images.githubusercontent.com/46537034/236636262-7e0d5447-0b8f-4751-a70d-7d1ccd18d6b5.png)

**Comment by yzqzss** [comment]
> sob ![image](https://user-images.githubusercontent.com/46537034/236636262-7e0d5447-0b8f-4751-a70d-7d1ccd18d6b5.png)

use `-g=-d` to pass the arg to `dokuWikiUploader`

**Comment by yzqzss** [comment]
lile `dokuWikiDumper xxxx --auto -u -g=-d`
